name: 'f1_data_analysis'
version: '1.0.0'
config-version: 2

profile: 'F1_Data_Analysis'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS silver;"
  - "CREATE SCHEMA IF NOT EXISTS gold;"

models:
  f1_data_analysis:
    silver:
      +schema: silver
      +materialized: view

    gold:
      +schema: gold
      +materialized: table

