name: 'nyc_parking_violations'
version: '1.0.0'
config-version: 2

profile: 'nyc_parking_violations'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS silver;"
  - "CREATE SCHEMA IF NOT EXISTS gold;"

models:
  nyc_parking_violations:
    silver:
      +schema: silver
      bronze_parking_violation_codes:
        +materialized: ephemeral
      bronze_parking_violations:
        +materialized: ephemeral
      silver_parking_violation_codes:
        +materialized: ephemeral
      silver_parking_violations:
        +materialized: ephemeral
      silver_violations_tickets:
        +materialized: view
      silver_violations_vehicles:
        +materialized: view

    gold:
      +schema: gold
      +materialized: table
